### ISSUE TITLE
in another language tap

### ISSUE THREAD

**Issue by MohammadAbuJajeh** [kiswanij/smart-desktop#5]
in another language tap didn't show the language name 
![in another language](https://cloud.githubusercontent.com/assets/19759038/15994512/61a5e220-310f-11e6-9f92-14593b044ed5.JPG)

**Comment by kiswanij** [comment]
Configuration issue in the metadata.
The summary field attribute didnt set in languages table , and the default is to get the second field in the fields list (except the id) .
However , i have updated it to include first and second fields by default if applicable.
